In [53]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [54]:
df = pd.read_csv('./py/ML/2_linear_reg_multivariate/homeprices.csv')
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [55]:
median_bedrooms = df.bedrooms.median()

In [56]:
df.bedrooms = df.bedrooms.fillna(median_bedrooms)

In [57]:
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [58]:
reg = linear_model.LinearRegression()
reg.fit(df[['area', 'bedrooms', 'age']], df.price)

LinearRegression()

In [59]:
reg.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [60]:
reg.intercept_

221323.00186540408

In [61]:
reg.predict([[3000,4,15]])

array([602590.07937407])

In [93]:
data_frame = pd.read_csv('./py/ML/2_linear_reg_multivariate/Exercise/hiring.csv')
data_frame

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [94]:
from word2number import w2n
data_frame['experience'] = data_frame['experience'].fillna('zero')
data_frame['experience'] = data_frame['experience'].apply(w2n.word_to_num)
median = data_frame['test_score(out of 10)'].median()
data_frame['test_score(out of 10)'] = data_frame['test_score(out of 10)'].fillna(median)
data_frame

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    8.0                           7      72000
7          11                    7.0                           8      80000

In [96]:
linear_reg = linear_model.LinearRegression()
linear_reg.fit(data_frame[['experience','test_score(out of 10)','interview_score(out of 10)']],data_frame['salary($)'])

LinearRegression()

In [106]:
linear_reg.predict([[2,9,6]])

array([53205.96797671])

In [107]:
linear_reg.predict([[12,10,10]])

array([92002.18340611])

In [108]:
linear_reg.predict([[0,8,9]])

array([52350.0727802])